// JsFromRoutes CacheKey 19a4352ea9760c6df7beebbb58b1e2e4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as notifications } from '~/api/NotificationsApi'
export { default as announcements } from '~/api/AnnouncementsApi'
