// JsFromRoutes CacheKey dc55785cf3337ae7c63d14490dbbedf1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/announcements'),
}
