// JsFromRoutes CacheKey f45fa0e459bf869d390757216b9c623b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/notifications'),
}
